import React from "react";
import { Poppins } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Utils/NavBar'

const poppins = Poppins({ 
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"], 
})

export const metadata = {
  title: 'sirAnimeIndo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} `} suppressHydrationWarning={true}>
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
